language: go
go_import_path: github.com/ReconfigureIO/brain

go:
  - 1.9


install:
- curl https://glide.sh/get | sh
- curl -LO https://s3.amazonaws.com/reconfigure.io/reco/releases/reco-master-x86_64-linux.zip
- unzip reco-master-x86_64-linux.zip
- sudo mv reco /usr/local/bin
- go get -t ../fixed
- go get -t ./bnn
- go get -t ../../sjwhitworth/golearn/base
- reco version

script:
  - make test
  - cd examples/inference/ && reco check
